[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
attacker = "GhB62wmFdADQeev3EkDpF9CahNmMbUd8RjDADWJg2ApR"
examples = "7Tvuosetih5XpvrfKmQeyhcmcqix8K9ijmbho4yV8e1V"
faucet = "HPZ99LcPpWiVqKmNKkUQPwyiytkpYg5tbMY4Sv3x9cvP"
vault = "6qsJF44KYSjfA5jDbivqqfcsjk18hR6ZJPMdj3ZTAWvu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
